services:
  dfp_pipeline:
    build: .
    volumes:
      - .:/app
#    command: ["--help", "-h", "run", "-l", "--log-level", "-e", "--load-env-file", "-i", "--indicators", "-s", "--sources", "-c", "--config", "-f", "--filter-indicators-string" ]
    env_file:
      - .env
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - ROOT_FOLDER=${ROOT_FOLDER}