[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dfpp"

version = "0.0.1"
description = "UNDP's Data Futures Platform Backend Pipeline"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    'azure-storage-blob',
    'aiohttp',
    'python-dotenv',
    'build',
    'openpyxl'
]

[tool.setuptools.packages.find]
where = ["./"]

[tool.distutils.bdist_wheel]
universal = true

[project.scripts]
dfp_pipeline = "dfpp.__main__:run_pipeline"